name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install deps
      run: make install

    - name: Build 
      run: make build

    - name: Deploy to GitHub Pages
      if: ${{ github.event_name != 'pull_request' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book